### ISSUE TITLE
feat(chassis-bloomery): record each candidate's package closure and derive semantic edges between members

### ISSUE THREAD

**Issue by iamacoffeepot** [iamacoffeepot/aether#6074]
## Observed

The shared-run selector (`SealedPolicySelection::select` / `build_plan` in `crates/aether-chassis-bloomery/src/bloomery/reactor/executor/runtime/scheduler.rs`) groups verify requests by bloom, composition-contract coverage, and an identical `starting_head`. The coordinator's blast-radius walk (`affected_closure` in `crates/aether-bloomery/src/reduce/coordination.rs`) expands over seal-declared `depends_on` edges and coverage. Neither reads the package graph, and nothing anywhere records what a candidate wrote in package terms — so a member whose change lands in a crate a sibling's gates compile is invisible to the operator and to the scheduler alike, even though `xtask`'s `reverse_dependency_closure` already answers the question for the verify lane's own scope.

### Bloom 0c5a157ecbe4 — what each candidate actually reaches

Closures below are `cargo xtask affected --base 451f4cf95` run over each candidate in a clean checkout; the gate's own resolution (`Scope`, which additionally screens workspace-level inputs) is quoted from each run's `verify.scope.log` where a run exists.

| member | changed packages | closure (reverse-dependency) | run | siblings in run |
|---|---|---|---|---|
| issue-6031 | xtask | **unbounded** — gate scope: *every workspace crate, a workspace-level input changed: `xtask/src/transform/verify/mod.rs`* | dispatch-8253 | none |
| retrospect-ab14a2538ac6 | aether-bloomery, aether-chassis-bloomery, aether-harness-bloomery | aether-bloomery, -console, -git, -github, -rest, aether-chassis-bloomery, aether-harness-bloomery, xtask (8) | dispatch-8280, 8317 | none |
| retrospect-de75c5ff95c2 | aether-chassis-bloomery | aether-chassis-bloomery, aether-harness-bloomery (2) | dispatch-8261 | none |
| retrospect-df2ca61518f1 | aether-chassis-bloomery | aether-chassis-bloomery, aether-harness-bloomery (2) | — | — |
| retrospect-e32787771dac | aether-bloomery-github | aether-bloomery-github, aether-chassis-bloomery, aether-harness-bloomery (3) | dispatch-8250 (pass, 7m25s) | none |
| retrospect-e8f7e7aac4ed | aether-chassis-bloomery (+ `docs/adr/`) | aether-chassis-bloomery, aether-harness-bloomery (2) | — | — |
| retrospect-6a1fe13e6695 | aether-bloomery, aether-bloomery-console, aether-chassis-bloomery | aether-bloomery, -console, -git, -github, -rest, aether-chassis-bloomery, aether-harness-bloomery, xtask (8) | dispatch-8311 (**red**, ejected) | none |

**Semantic edges** (A depends on B when B's changed package is inside A's closure), none of which is declared, shown, or used anywhere today:

- `issue-6031` → every other member (its scope is the whole workspace, so it compiles every sibling's write).
- `retrospect-ab14a2538ac6` → `issue-6031` (xtask), `retrospect-e32787771dac` (aether-bloomery-github), `retrospect-de75c5ff95c2` / `-df2ca61518f1` / `-e8f7e7aac4ed` (aether-chassis-bloomery), `retrospect-6a1fe13e6695`.
- `retrospect-de75c5ff95c2`, `-df2ca61518f1`, `-e8f7e7aac4ed`, `-e32787771dac`, `-6a1fe13e6695` → each other and `-ab14a2538ac6`, through `aether-chassis-bloomery`.

**Grouping today vs. closure-aware grouping.** Every shared run this bloom produced carried exactly one member (`shared_run_members`: 8250, 8253, 8261, 8280, 8311, 8317, 8330, 8333 — one row each), so no member paid for a sibling's sweep. The reason is base disagreement, not closure: eager integration advanced `starting_head` between constructs, so no two requests agreed on a construct base. Closure-aware grouping would not have recovered much *here* — six of the seven closures intersect on `aether-chassis-bloomery` — and that is the finding worth recording: the safe group is the **disjoint** one, and this bloom has almost none. What closure-awareness does give, immediately, is (i) a rule that never coalesces `issue-6031` (unbounded) with a two-crate sibling, which would have made the sibling pay a full sweep, and (ii) a stated reason on each run so a one-member run reads as "everything else intersected" rather than as nothing to say.

**Red run classification.** `dispatch-8311-step-0` failed `verify.clippy` / `verify.test` with `error[E0063]: missing fields scope_model_override and scope_seat in initializer of aether_bloomery::CommissionShowView --> xtask/src/bloom/amend/tests.rs:49`. It was a **single-member** run; `retrospect-6a1fe13e6695` added those fields in `aether-bloomery` and left xtask's initializers unrepaired, and xtask is listed in that run's own `verify.scope.log` closure. No sibling in the bloom wrote an xtask path (only `issue-6031` touches xtask, in a different run). So this is a **lone defect** — the candidate's own miss of a reader inside its closure, the class the readers table in #6068 targets — not a two-member semantic conflict. Had it shared a run with a member that did write xtask, path attribution (`attribute_gate`, `crates/aether-chassis-bloomery/src/bloomery/verify/ownership/`) would have charged that sibling and ejected it.

## Expected

1. Each candidate's **changed packages** and **reverse-dependency closure** are recorded at construct capture, with `closure: null` meaning *unbounded* (a whole-workspace sweep) and never "reaches nothing".
2. The coordinator's reads serve those per member, and the **derived semantic edges** for a bloom, without adding a persisted value to the wire-frozen journal graph — the evidence is already addressable from the member's dispatch row.
3. The console board carries a `DEPENDS` column naming the members a member semantically depends on, and each bloom's shared-run grouping reason. An unread bloom must render as unknown, never as independence.
4. The scheduler half — grouping by closure-disjointness, admitting intersecting closures only once attribution can name an A↔B conflict, and classifying every bounce — is an ADR decision, not part of this issue.

## Surface

- `xtask/**`
- `crates/aether-bloomery/**`
- `crates/aether-chassis-bloomery/**`
- `crates/aether-bloomery-console/**`
- `docs/adr/**`

**Comment by iamacoffeepot** [comment]
Closed in the retirement of the first bloomery (PR #6081, commit 0a3c9f566): the coordinator, console, lanes, and their scripts this issue targets no longer exist on main. The clean-room rewrite (ADR-0220 onward) tracks its own issues; if this idea still applies there, it will be refiled against the new code.
