### ISSUE TITLE
refactor(test-fixtures): consolidate fixtures into one bundle component and migrate the suite

### ISSUE THREAD

**Issue by iamacoffeepot** [iamacoffeepot/aether#2043]
## Description

> Reorganize `aether-test-fixtures` into a **fixtures directory of single-output crates**, off the main workspace member line: one shared `kinds` rlib, one **MAIN bundle** cdylib that consolidates the bulk of the fixtures behind a single `export!()`, and **two standalone cdylib crates** for the typed↔reshaped cross-module replace test (which structurally needs two distinct wasm binaries). No `[[example]]` targets, no `runtime` feature gate, no xtask special-casing — every crate is one cdylib, discovered structurally.

Supersedes the earlier single-crate bundle plan (a `["cdylib","rlib"]` crate + `runtime` feature + a lone `[[example]]` satellite). That plan was bounced: it routed `stateful_replace_typed` into the bundle, contradicting the documented invariant that the typed↔reshaped cross-module replace needs two distinct binaries (a single-actor module emits `namespace: None`, so `resolve_replace_target` can only reach it via the entry-fallback — `export: None` + a `None` stored tag — which a bundled load can't produce because the bundle entry is `Probe`). This design keeps consolidation for everything that *can* bundle and pays the two-binary cost only where the test forces it.

## Problem statement

`aether-test-fixtures` is an rlib of shared `Kind` types whose 12 wasm fixtures live as per-example cdylibs (`[[example]]` targets). Every load site names a per-fixture stem and the `aether.kinds.inputs` discovery surface is fragmented across 12 modules. The bulk of these fixtures are independent single- or multi-actor components that can be consolidated into one bundle; the exception is the `stateful_replace_typed` / `stateful_replace_reshaped` pair, which the ADR-0113 decode-miss test (`typed_state_decode_miss_boots_fresh`) replaces one-for-the-other and therefore needs as two distinct binaries.

**Done** is observable as: `crates/aether-test-fixtures/` is a container directory (no crate at its root) holding four workspace-member crates — `kinds` (rlib types), `bundle` (cdylib, 18 exported actors under one `export!()`), `stateful-typed` (cdylib, single actor), `stateful-reshaped` (cdylib, single actor) — listed in the workspace `members` grouped off the main line; the cross-build emits exactly three fixture wasm artifacts; a repo-wide grep finds no `[[example]]` fixture stems; the typed↔reshaped replace test loads the typed satellite as entry and replaces it with the reshaped satellite; and `cargo nextest run -p aether-substrate-bundle` is green. No `runtime` feature, no xtask `--no-default-features` ordering — each crate is one cdylib discovered by the existing structural rule (cdylib target + `aether-actor` dep).

### Chosen approach

A fixtures directory of single-output crates. `crates/aether-test-fixtures/` becomes a pure container directory holding:

- **`kinds/`** — `aether-test-fixtures-kinds`, a `no_std` rlib carrying the shared `Kind` types (`Bump`, `CountQuery`, `CountReport`, the cube/mat4/widget/http/matrix/inline/source kinds, and `stateful_replace`'s `CounterState`). Host-visible: the ~18 host test files import their fixture types from here. The two reshaped/typed `CounterState` *variants* do **not** live here — each satellite defines its own (a different `Kind::ID` is the whole point of the decode-miss test).
- **`bundle/`** — `aether-test-fixtures-bundle`, a `cdylib` whose `src/` carries the 18 consolidated actors under one `aether_actor::export!(Probe, …)` (`Probe` first to preserve the entry-load `export: None` contract). This is every former fixture **except** the typed/reshaped Counters — including the genuinely multi-actor `stateful_replace` (`Counter` + `Sidecar`), which bundles fine.
- **`stateful-typed/`** — `aether-test-fixtures-stateful-typed`, a single-actor `cdylib` (`Counter`, `NAMESPACE = "stateful.typed"`, original `CounterState`). The replace **source**.
- **`stateful-reshaped/`** — `aether-test-fixtures-stateful-reshaped`, a single-actor `cdylib` (`Counter`, same `NAMESPACE = "stateful.typed"`, a reshaped `CounterState` with an added field). The replace **target**.

Each cdylib crate depends on `aether-actor`, `aether-capabilities` (`default-features = false, features = ["render"]` — the wasm-header-only marker layer), `aether-kinds`, `aether-test-fixtures-kinds`, and the math/data/serde deps its bodies need. Because each crate emits exactly one cdylib, the existing xtask `discover_components` finds all three structurally with **zero** special-casing — no `from_example` path, no `--no-default-features`, no output rename. The three artifacts are `aether_test_fixtures_bundle.wasm`, `aether_test_fixtures_stateful_typed.wasm`, `aether_test_fixtures_stateful_reshaped.wasm`.

**Why the replace pair stays standalone.** The `typed_state_decode_miss_boots_fresh` test loads the typed wasm, bumps its persisted counter, then `replace_component`s it with the reshaped wasm and asserts the recovered count is `0` (the generated `on_rehydrate` decode-misses against the reshaped `CounterState::ID` and boots fresh). Resolving a replace into a single-actor module only succeeds via the entry-fallback (`export: None` + `None` stored tag), which requires the typed side to have been loaded as a module **entry** — impossible from the bundle (entry is `Probe`). So both must be standalone, single-actor, entry-loaded crates. This is the one irreducible two-binary cost; the test guards a real safety property (no silent state corruption across a hot-reload that changes the persisted state's shape) and cannot be shrunk to one binary without testing something else.

### Rejected options

- **Single `["cdylib","rlib"]` crate + `runtime` feature + `[[example]]` satellite** (the bounced plan) — contradicts the two-distinct-binaries invariant for the replace pair, and forces xtask `--no-default-features` example-before-lib ordering. Superseded.
- **All three as `[[example]]` cdylibs** — clean and fully discovery-native, but `[[example]]` over a test fixture communicates "usage example" to a human reader and reads as a build hack. Rejected on legibility grounds.
- **Feature-rebuild + output rename** (one crate, mutually-exclusive features, build N× and rename the colliding `aether_test_fixtures.wasm`) — breaks the structural discovery model: a feature is not a Cargo target, so `cargo metadata` reports one cdylib regardless, forcing a bespoke per-crate build recipe in xtask. Rejected.
- **Hand-written WAT reshaped fixture** — would reimplement the FFI ABI, codec bytes, hashed `Kind::ID`s, and custom sections by hand, and would stop exercising the macro-generated `on_rehydrate` the test exists to verify. Rejected.
- **Delete the decode-miss test** — drops the only behavioral guard against silent hot-reload state corruption. Rejected.

### Affected surfaces

- `crates/aether-test-fixtures/` — restructured from one crate into a container dir of four crates (`kinds`, `bundle`, `stateful-typed`, `stateful-reshaped`); all `[[example]]` removed.
- Root `Cargo.toml` `members` — drop `crates/aether-test-fixtures`, add the four sub-crates (explicit list per the Qodana-TOML convention), grouped with a comment off the main line.
- `crates/aether-substrate-bundle/Cargo.toml` — the `aether-test-fixtures` dev-dep becomes `aether-test-fixtures-kinds` (the type surface the tests assert against).
- `crates/aether-substrate-bundle/tests/*.rs` (~18 files) + `tests/fleetbench/mod.rs` — load-site migration to the new stems (`aether_test_fixtures_bundle` + `export: Some("<NAMESPACE>")` per the table; the two replace sites name the satellite stems, loaded `export: None`); and the type-import repoint `aether_test_fixtures::` → `aether_test_fixtures_kinds::`.
- `xtask` — **no change** beyond what structural discovery already does (three one-cdylib crates are found generically). The bounced plan's `inventory.rs` / `main.rs` `--no-default-features` ordering is not needed.
- No wire change, no public-trait change, no ADR (a test-fixtures + workspace-layout refactor consistent with ADR-0096 / issue-439).

### Load-site migration table (namespaces read from `origin/main`)

| Actor → `export` namespace | Home |
|---|---|
| `Probe` → `test_fixture_probe` (bundle entry), `ProbeWithConfig` → `test_fixtures_probe_with_config` | bundle |
| `RootManager` → `ui.root`, `Panel` → `ui.panel` | bundle |
| `Cube` → `cube` | bundle |
| `MatSource` → `mat4_source`, `Vec4Observer` → `vec4_observer` | bundle |
| `UiWidget` → `test_fixtures_ui_widget` | bundle |
| `HttpHandler` → `web` | bundle |
| `SourceObserver` → `test.source_observer` | bundle |
| `MatrixParent` → `test.matrix.parent`, `MatrixChild` → `test.matrix.child` | bundle |
| `InlineParent` → `test.inline.parent`, `InlineStatefulParent` → `test.inline.stateful_parent`, `InlineStatefulChild` → `test.inline.stateful_child`, `InlineDespawnParent` → `test.inline.despawn_parent` (`InlineChild` / `InlineDespawnChild` ride as types) | bundle |
| `Counter` → `stateful.counter`, `Sidecar` → `stateful.sidecar` | bundle (multi-actor) |
| `Counter` → `stateful.typed` (`export: None`, entry) | **stateful-typed** crate |
| `Counter` → `stateful.typed`, reshaped `CounterState` (`export: None`, entry) | **stateful-reshaped** crate |

18 exported actors in the bundle; `http_handler` → `web` and `ui_widget` → `test_fixtures_ui_widget` are the two namespaces that don't echo their source module. `cap_registry.rs`'s `aether_kit` load is unrelated and stays.

## Implementation plan

**Model: `model:opus`** — cross-crate (4 new crates + bundle tests), >500 LOC relocated, plus the host type-import repoint; the body moves are mechanical against the table but the crate split + member wiring carry judgment. **Size: L.** **Branch from fresh `main`** (the existing `.claude/worktrees/issue-2043` worktree holds the bounced single-crate work — reuse its relocated body content and verified namespace table as reference, but rebuild the crate structure to this design).

1. **Shared kinds crate** — create `crates/aether-test-fixtures/kinds/` (`aether-test-fixtures-kinds`, `#![no_std]` rlib) holding the shared `Kind` types currently at the `aether-test-fixtures` root (everything except the two satellite `CounterState` variants). — *Verify: `cargo build -p aether-test-fixtures-kinds` host-side; the type set matches what the host tests import.*
2. **Bundle crate** — create `crates/aether-test-fixtures/bundle/` (`aether-test-fixtures-bundle`, `[lib] crate-type = ["cdylib"]`) with `src/` carrying the 18 bundle actors (relocated from the former examples, `use aether_test_fixtures::` → `use aether_test_fixtures_kinds::`) under one `export!(Probe, …)` (`Probe` first). Deps mirror `aether-kit`'s wasm-marker shape. — *Verify: `cargo build -p aether-test-fixtures-bundle --target wasm32-unknown-unknown` emits `aether_test_fixtures_bundle.wasm`; its `aether.kinds.inputs` lists 18 actors.*
3. **Typed + reshaped satellite crates** — create `crates/aether-test-fixtures/stateful-typed/` and `.../stateful-reshaped/`, each a single-actor cdylib (`Counter`, `NAMESPACE = "stateful.typed"`), the first with the original `CounterState`, the second with the reshaped one (added field), each its own `export!(Counter)`. — *Verify: both cross-build to distinct wasm; no duplicate-symbol; each `aether.kinds.inputs` is single-actor (`namespace: None`).*
4. **Workspace wiring** — root `Cargo.toml`: drop `crates/aether-test-fixtures`, add the four sub-crates to `members` (explicit, grouped off the main line). `crates/aether-substrate-bundle/Cargo.toml`: dev-dep `aether-test-fixtures` → `aether-test-fixtures-kinds`. — *Verify: `cargo metadata` lists the four crates; xtask `discover_components` finds the three cdylibs with `from_example = false`.*
5. **Migrate load sites + repoint types** — across the ~18 `tests/*.rs` + `fleetbench/mod.rs`: bundle fixtures → stem `aether_test_fixtures_bundle` + `export: Some("<NAMESPACE>")` per the table; the typed load → stem `aether_test_fixtures_stateful_typed`, `export: None`; the reshaped replace → stem `aether_test_fixtures_stateful_reshaped`, `export: None`; and repoint type imports `aether_test_fixtures::` → `aether_test_fixtures_kinds::`. The `multi_actor` non-entry replace becomes bundle `ui.root` → `ui.panel`. — *Verify: each suite (probe family, replace, DAG, widget-cost, http, matrix-sweep, inline-child, source, autoload) compiles and passes; `typed_state_decode_miss_boots_fresh` is green.*
6. **Green-gate** — `scripts/preflight.sh`; `cargo nextest run -p aether-substrate-bundle` green; cross-build emits exactly the three fixture wasm; grep confirms no `[[example]]` fixture stems remain. — *Verify: preflight stamp; PR closes #2043.*

## Side findings

- The bundle's `aether.kinds.inputs` now lists 18 actors in one module, so `describe_component` on the loaded bundle returns the union of those fixtures' handler kinds — expected, but a behavior change for any test that asserted a per-fixture handler set. — `crates/aether-test-fixtures/bundle/src/`

**Comment by iamacoffeepot** [comment]
**Bounced to Design** (from Ready)

Adopt the runtime-feature-gate model (the `aether-kit` `feature = "runtime"` pattern) instead of the two-crate `-kinds` split. The gate keeps the shared kind types host-visible from `aether-test-fixtures` itself (host builds `default-features = false` and see only the `no_std` type lib; the wasm cross-build takes `--features runtime` and gets the actor bodies + one `export!()`), so the `-kinds` extraction (#2042, now closed) is unnecessary and the multi-PR umbrella (#2041, now closed) collapses into this single single-crate PR.

Re-design needed:
- `aether-test-fixtures` becomes `crate-type = ["cdylib", "rlib"]` with `default = ["runtime"]`, `runtime = []`; the 19 actor bodies move from `examples/` into a `#[cfg(feature = "runtime")] mod runtime` behind one `export!()`; `aether-actor` / `aether-capabilities` / `aether-kinds` / `tracing` promote dev→normal deps (native-inert, wasm-export).
- The kind types stay at the crate root, so the ~14 host test files keep `use aether_test_fixtures::{…}` — no type-import repoint. Only the load-site migration (bundle stem + `export: Some("<NAMESPACE>")`) remains.
- The `stateful_replace_reshaped` satellite stays a physically distinct wasm as the one surviving `[[example]]` of `aether-test-fixtures`, cross-built `--no-default-features` so the lib `export!()` is gated off and there is no duplicate FFI symbol.

**Comment by iamacoffeepot** [comment]
**Bounced to Design** — the migration table contradicts a documented invariant on `origin/main`. Implementation is ~95% done and staged uncommitted in the worktree (green except the one blocked test); it is **not** committed or pushed. Re-scope is a small table delta, then resume in the existing worktree — see below.

## The defect

The §Design migration table routes `stateful_replace_typed::Counter` (namespace `stateful.typed`) **into the bundle**, keeps `stateful_replace_reshaped` as a single-actor satellite, and resolves the typed↔reshaped cross-module replace via `export: Some("stateful.typed")`. That cannot resolve:

- A **single-actor** wasm module emits no `ActorBoundary`, so its `aether.kinds.inputs` group is `namespace: None` (verified: `crates/aether-substrate/src/actor/wasm/kind_manifest.rs:248-258`; the name lives only in the separate `aether.namespace` section).
- `resolve_replace_target` (`crates/aether-capabilities/src/trampoline.rs:474-530`) matches the new module's actors by `a.namespace`. For a single-actor module every `namespace` is `None`, so a `ReplaceComponent` into it resolves neither by `export: Some("stateful.typed")` (→ `export "stateful.typed" not found; exported types: []`) nor by the bare-replace stored-tag path. The only path that reaches a single-actor module is the entry-fallback: `export: None` **with a `None` stored tag**.
- A `None` stored tag requires the typed Counter to have been loaded as the module **entry** (`export: None`). But the bundle entry is `Probe` (kept first to preserve the probe's `export: None` contract), so the typed load must use `export: Some("stateful.typed")` → non-`None` tag → the reshaped replace can never resolve.

**Decisive corroboration:** `origin/main`'s own `aether-test-fixtures/Cargo.toml` documents exactly this — *"NOT bundled: `stateful_replace{,_typed,_reshaped}` … a cross-module replace needs two distinct wasm binaries, so these cannot share a bundle."* The plan's table overlooked this pre-existing invariant.

## Recommended resolution (forced by the invariant; matches prior art)

Keep `stateful_replace_typed` as a single-actor satellite `[[example]]` alongside `stateful_replace_reshaped` → **three** fixture artifacts (`aether_test_fixtures.wasm` + `stateful_replace_typed.wasm` + `stateful_replace_reshaped.wasm`), bundle export count **18** not 19. The typed load is then entry (`export: None`, `None` tag) and both the same-binary typed replace and the cross-module reshaped replace resolve via entry-fallback, unchanged from `origin/main`. (`stateful_replace::Counter`+`Sidecar` is genuinely multi-actor and stays in the bundle correctly.)

Rejected alternatives: a substrate change to emit single-actor namespaces in `aether.kinds.inputs` (out of scope — plan said no trait change); a dummy second actor to make the reshaped satellite multi-actor (a hack).

§Design edits needed: migration-table rows for `stateful_replace_typed` (satellite, not bundle), the "exactly two fixture artifacts" / "19 exported" Done criteria → three / 18, and the xtask "exactly two artifacts" verify.

## What is done and green (staged in the worktree, uncommitted)

37 files: manifest (cdylib+rlib, `runtime` feature, deps promoted), 11 bodies relocated via `git mv` into `src/runtime/` under one `export!()`, xtask `--no-default-features` + example-before-lib ordering, all ~18 load-site migrations. `cargo fmt` / `cargo clippy --workspace -D warnings` (0 warnings) / `cargo doc` (fixtures clean) all pass; the cross-build emits the expected artifacts with no duplicate symbols. The only deterministic test failure is `typed_state_decode_miss_boots_fresh` — the blocker above. (The two transient fleetbench fails were heavy-test fork flakes, green in isolation.)

**Empirically settled** (the plan's open xtask question): `cargo build --examples [--no-default-features]` does **not** emit the package lib cdylib to the shared path — only `examples/<stem>.wasm` appears. The load-bearing part is `--no-default-features` on the example plan (building the satellite with default features duplicate-symbols `init`/`receive_p32` against the runtime-on lib); the defensive example-before-lib ordering is retained regardless.
